
import { Dish, CategoryConfig } from './types';

// Initial Categories Configuration
export const DEFAULT_CATEGORIES: CategoryConfig[] = [
  // Front Page
  { id: 'cat_hot', name: '热菜小炒', isFront: true },
  { id: 'cat_cold', name: '爽口凉菜', isFront: true },
  // Back Page
  { id: 'cat_staple', name: '传统主食', isFront: false },
  { id: 'cat_soup', name: '汤粥面食', isFront: false },
  { id: 'cat_drinks', name: '酒水饮料', isFront: false },
];

export const MENU_ITEMS: Dish[] = [
  // --- 爽口凉菜 (Cold) ---
  {
    id: 'c1',
    name: '老醋花生米',
    price: 12,
    category: '爽口凉菜',
    description: '酸甜适口，下酒神器',
    imageUrl: '',
  },
  {
    id: 'c2',
    name: '刀拍黄瓜',
    price: 10,
    category: '爽口凉菜',
    description: '清脆爽口，解腻首选',
    imageUrl: '',
    spicyLevel: 1,
  },
  {
    id: 'c3',
    name: '红油猪耳',
    price: 22,
    category: '爽口凉菜',
    description: '红油拌之，脆骨爽脆',
    imageUrl: '',
    spicyLevel: 2,
    popular: true,
  },
  {
    id: 'c4',
    name: '皮蛋豆腐',
    price: 14,
    category: '爽口凉菜',
    description: '嫩滑爽口，清热去火',
    imageUrl: '',
  },
  {
    id: 'c5',
    name: '酱驴肉(盘)',
    price: 48,
    category: '爽口凉菜',
    description: '秘制卤肉，切片装盘',
    imageUrl: '',
    popular: true,
  },
  {
    id: 'c6',
    name: '凉拌土豆丝',
    price: 8,
    category: '爽口凉菜',
    description: '酸辣开胃，口感脆嫩',
    imageUrl: '',
    spicyLevel: 1,
  },
  {
    id: 'c7',
    name: '小葱拌豆腐',
    price: 8,
    category: '爽口凉菜',
    description: '一清二白，原汁原味',
    imageUrl: '',
  },
  {
    id: 'c8',
    name: '果仁菠菜',
    price: 12,
    category: '爽口凉菜',
    description: '营养丰富，清淡爽口',
    imageUrl: '',
  },
  {
    id: 'c9',
    name: '东北大拉皮',
    price: 16,
    category: '爽口凉菜',
    description: '麻酱浓郁，Q弹爽滑',
    imageUrl: '',
  },
  {
    id: 'c10',
    name: '老虎菜',
    price: 10,
    category: '爽口凉菜',
    description: '香菜青椒，辛辣开胃',
    imageUrl: '',
    spicyLevel: 2,
  },
  {
    id: 'c11',
    name: '酱牛肉',
    price: 58,
    category: '爽口凉菜',
    description: '纹理清晰，肉质紧实',
    imageUrl: '',
  },
  {
    id: 'c12',
    name: '泡椒凤爪',
    price: 18,
    category: '爽口凉菜',
    description: '酸辣爽口，越嚼越香',
    imageUrl: '',
    spicyLevel: 2,
  },

  // --- 传统主食 ---
  {
    id: 'd1',
    name: '精品纯瘦驴肉火烧',
    price: 12,
    category: '传统主食',
    description: '肉香浓郁，解馋不腻',
    imageUrl: '',
    popular: true,
  },
  {
    id: 'd2',
    name: '肥瘦相间驴肉火烧',
    price: 10,
    category: '传统主食',
    description: '经典搭配，香润口',
    imageUrl: '',
    popular: true,
  },
  {
    id: 'd3',
    name: '驴板肠火烧',
    price: 14,
    category: '传统主食',
    description: '口感Q弹，越嚼越香',
    imageUrl: '',
  },
  {
    id: 'd4',
    name: '焖子火烧',
    price: 5,
    category: '传统主食',
    description: '软糯咸香，经济实惠',
    imageUrl: '',
  },
  {
    id: 'd5',
    name: '青椒驴肉火烧',
    price: 11,
    category: '传统主食',
    description: '青椒清脆，解腻提味',
    imageUrl: '',
  },
  {
    id: 'd6',
    name: '特制全福火烧',
    price: 18,
    category: '传统主食',
    description: '肉肠焖子，一口满足',
    imageUrl: '',
    popular: true,
  },
  {
    id: 'd7',
    name: '老汤火烧皮',
    price: 2,
    category: '传统主食',
    description: '酥脆掉渣，面香浓郁',
    imageUrl: '',
  },
  {
    id: 'st1',
    name: '米饭',
    price: 2,
    category: '传统主食',
    description: '五常大米，粒粒分明',
    imageUrl: '',
  },
  {
    id: 'st2',
    name: '馒头',
    price: 1,
    category: '传统主食',
    description: '手工大馒头，麦香',
    imageUrl: '',
  },
  {
    id: 'st3',
    name: '鸡蛋炒面',
    price: 12,
    category: '传统主食',
    description: '锅气十足，家常味道',
    imageUrl: '',
  },
  {
    id: 'st4',
    name: '驴肉炒饭',
    price: 18,
    category: '传统主食',
    description: '驴肉丁炒制，香气扑鼻',
    imageUrl: '',
  },

  // --- 热菜小炒 ---
  {
    id: 'h1',
    name: '熘肝尖',
    price: 28,
    category: '热菜小炒',
    description: '大火爆炒，肝尖滑嫩',
    imageUrl: '',
  },
  {
    id: 'h2',
    name: '京酱肉丝',
    price: 32,
    category: '热菜小炒',
    description: '酱香浓郁，老少皆宜',
    imageUrl: '',
    popular: true,
  },
  {
    id: 'h3',
    name: '素炒饼',
    price: 10,
    category: '热菜小炒',
    description: '蒜香扑鼻，量大管饱',
    imageUrl: '',
  },
  {
    id: 'h4',
    name: '葱爆羊肉',
    price: 38,
    category: '热菜小炒',
    description: '葱香肉嫩，回味无穷',
    imageUrl: '',
  },
  {
    id: 'h5',
    name: '宫保鸡丁',
    price: 26,
    category: '热菜小炒',
    description: '酸甜微辣，花生酥脆',
    imageUrl: '',
    spicyLevel: 1,
  },
  {
    id: 'h6',
    name: '酸辣土豆丝',
    price: 12,
    category: '热菜小炒',
    description: '家常经典，酸辣下饭',
    imageUrl: '',
    spicyLevel: 2,
  },
  {
    id: 'h7',
    name: '鱼香肉丝',
    price: 24,
    category: '热菜小炒',
    description: '酸甜微辣，下饭神器',
    imageUrl: '',
    spicyLevel: 1,
  },
  {
    id: 'h8',
    name: '软炸里脊',
    price: 28,
    category: '热菜小炒',
    description: '外酥里嫩，椒盐蘸食',
    imageUrl: '',
  },
  {
    id: 'h9',
    name: '地三鲜',
    price: 18,
    category: '热菜小炒',
    description: '茄子土豆青椒，鲜美',
    imageUrl: '',
  },
  {
    id: 'h10',
    name: '木须肉',
    price: 22,
    category: '热菜小炒',
    description: '鸡蛋木耳，营养均衡',
    imageUrl: '',
  },
  {
    id: 'h11',
    name: '蒜苔炒肉',
    price: 20,
    category: '热菜小炒',
    description: '家常味道，超级下饭',
    imageUrl: '',
  },
  {
    id: 'h12',
    name: '孜然羊肉',
    price: 42,
    category: '热菜小炒',
    description: '孜然浓郁，羊肉鲜嫩',
    imageUrl: '',
    spicyLevel: 1,
  },
  {
    id: 'h13',
    name: '回锅肉',
    price: 32,
    category: '热菜小炒',
    description: '肥而不腻，川味经典',
    imageUrl: '',
    spicyLevel: 2,
  },
  {
    id: 'h14',
    name: '尖椒干豆腐',
    price: 16,
    category: '热菜小炒',
    description: '东北特色，滑嫩入味',
    imageUrl: '',
    spicyLevel: 1,
  },

  // --- 汤粥面食 ---
  {
    id: 's1',
    name: '全驴杂汤',
    price: 15,
    category: '汤粥面食',
    description: '汤色乳白，鲜美无比',
    imageUrl: '',
    popular: true,
  },
  {
    id: 's2',
    name: '小米粥',
    price: 2,
    category: '汤粥面食',
    description: '养胃金黄，火烧绝配',
    imageUrl: '',
  },
  {
    id: 's3',
    name: '紫菜蛋花汤',
    price: 6,
    category: '汤粥面食',
    description: '清淡鲜美，饭后一碗',
    imageUrl: '',
  },
  {
    id: 's4',
    name: '西红柿鸡蛋汤',
    price: 8,
    category: '汤粥面食',
    description: '酸甜开胃，家常味道',
    imageUrl: '',
  },
  {
    id: 's5',
    name: '驴肉馄饨',
    price: 12,
    category: '汤粥面食',
    description: '皮薄馅大，汤鲜味美',
    imageUrl: '',
  },
  {
    id: 's6',
    name: '疙瘩汤',
    price: 10,
    category: '汤粥面食',
    description: '面疙瘩劲道，汤汁浓稠',
    imageUrl: '',
  },

  // --- 酒水饮料 ---
  {
    id: 'k1',
    name: '北冰洋汽水',
    price: 5,
    category: '酒水饮料',
    description: '老北京风味，气足沙口',
    imageUrl: '',
  },
  {
    id: 'k2',
    name: '雪花啤酒',
    price: 6,
    category: '酒水饮料',
    description: '勇闯天涯，清凉一夏',
    imageUrl: '',
  },
  {
    id: 'k3',
    name: '红星二锅头',
    price: 18,
    category: '酒水饮料',
    description: '纯粮酿造，度数适中',
    imageUrl: '',
  },
  {
    id: 'k4',
    name: '可口可乐',
    price: 3,
    category: '酒水饮料',
    description: '快乐肥宅水',
    imageUrl: '',
  },
  {
    id: 'k5',
    name: '酸梅汤',
    price: 6,
    category: '酒水饮料',
    description: '冰镇解暑，酸甜解腻',
    imageUrl: '',
  },
  {
    id: 'k6',
    name: '王老吉',
    price: 5,
    category: '酒水饮料',
    description: '怕上火喝王老吉',
    imageUrl: '',
  },
  {
    id: 'k7',
    name: '牛栏山陈酿',
    price: 20,
    category: '酒水饮料',
    description: '白瓶二锅头，够劲',
    imageUrl: '',
  },
  {
    id: 'k8',
    name: '鲜榨玉米汁',
    price: 18,
    category: '酒水饮料',
    description: '香甜浓郁，热饮推荐',
    imageUrl: '',
  },
  {
    id: 'k9',
    name: '江小白',
    price: 25,
    category: '酒水饮料',
    description: '简单纯粹，适合小酌',
    imageUrl: '',
  },
];
